name: Run e2e tests workflow

on:
  workflow_call:
    inputs:
      # start command for local server, used by Cypress action
      start-command:
        type: string
        default: 'npm run dev'
      # wait for url to become available, used by Cypress action
      wait-on-url:
        type: string
        default: 'http://localhost:3000/'
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      SSH_KEY:
        required: true
      CYPRESS_RECORD_KEY: 
        required: true
jobs:
  e2e-tests:
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 4 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    runs-on: ubuntu-latest
    steps:
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.9'
          registry-url: https://registry.npmjs.org/
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up SSH key
        run: bash .github/workflows/setup-ssh.sh ${{ secrets.SSH_KEY }}
      # Cypress installs and caches dependencies
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: ${{ inputs.start-command }}
          wait-on: ${{ inputs.wait-on-url }}
          wait-on-timeout: 120
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
